# Generated by Django 4.2.10 on 2024-03-04 16:50

import catalog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CatalogCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="Название"),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True, verbose_name="Опубликовано"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=200, verbose_name="Слаг"),
                ),
                (
                    "weight",
                    models.PositiveSmallIntegerField(
                        default=100, verbose_name="Вес"
                    ),
                ),
            ],
            options={
                "db_table": "catalog_category",
            },
        ),
        migrations.CreateModel(
            name="CatalogTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="Название"),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True, verbose_name="Опубликовано"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=200, verbose_name="Слаг"),
                ),
            ],
            options={
                "db_table": "catalog_tag",
            },
        ),
        migrations.AlterField(
            model_name="catalogitem",
            name="text",
            field=models.TextField(
                validators=[catalog.models.validate_luxurious_text],
                verbose_name="Текст",
            ),
        ),
        migrations.AddField(
            model_name="catalogitem",
            name="category",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.catalogcategory",
            ),
        ),
        migrations.AddField(
            model_name="catalogitem",
            name="tag",
            field=models.ManyToManyField(to="catalog.catalogtag"),
        ),
    ]
