# Generated by Django 4.2.10 on 2024-03-04 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_catalogitem_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="catalogitem",
            name="category",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.catalogcategory",
            ),
        ),
    ]
